### ISSUE TITLE
conserve gutter with Mobile

### ISSUE THREAD

**Issue by lhapaipai** [Spope/MiniMasonry.js#1]
Hello,
Thanks for your library, she's light and does her job perfectly !

There's a little bug when you're viewport is less than 530px
```javascript
// l62
this._count = Math.floor((this._width - this._gutter) / (this.conf.baseWidth + this.conf.gutter));

// 93
this._columns[shortest]  += this._sizes[index] + this.conf.gutter;//margin-bottom
```
  
you should prefer
```javascript
// l62
this._count = Math.floor((this._width - this._gutter) / (this.conf.baseWidth + this._gutter));


// 93
this._columns[shortest]  += this._sizes[index] + this._gutter;//margin-bottom
```

**Comment by Spope** [comment]
Thanks for opening this issue.
You're absolutely right, those were mistakes during the layout computing. After considering fixing it the way you did, I have done the following changes as some decisions were to opinionated in this inital version.

The gutter will no longer be reduced (to 5px) under 530px, but dynamically, when only 1 column can be displayed. The gutter reduced width is now a new parameter : "ultimateGutter"
The ultimateGutter value will be applied on each side of each element when only 1 column is shown. Side gutter can then disappear if screen width requires it.

Again, thanks for taking time to top open an issue.

**Comment by lhapaipai** [comment]
Great !!
