### ISSUE TITLE
Why should I not just only use native CSS Flexbox?

### ISSUE THREAD

**Issue by TimSusa** [Spope/MiniMasonry.js#13]
Hi Guys, 

I spent little minutes just for the sake to understand what do you want to achieve with your project. I mean it might turn out I do not really understand what is going on here and why I should use your project and not just only Native Browser CSS Flex Box Layouts? If it turns out to be the case, would you might be so kind and explain more in your documentation what the benefit of your project is?

Thanks and best regards

Tim.

**Comment by Spope** [comment]
Hi @TimSusa,
This library was born in a time where flexbox and grid layout wasn't a thing (way before putting it on GH), and JS was the only way to achieve this. Today you can ideed make something similar without JS but with some limitations, the order of the elements is one of them. You can check [here](https://css-tricks.com/piecing-together-approaches-for-a-css-masonry-layout/) some good examples without JS and some with a little bit of JS.
So I am pretty sure you can spend some time to achieve what you want for a specific use case, or use a library with its options to achieve that specific need.
