### ISSUE TITLE
Height issue

### ISSUE THREAD

**Issue by mehtabfarooq** [Spope/MiniMasonry.js#16]
Hi, thanks for creating such an awesome library. I am facing an issue while images are loading, it is not getting their full height. I can't use fixed height in my case, so what the solution would be apart for fixed height for images?

**Comment by Spope** [comment]
If you don't know your image's height / width, my guess would be to listen to image's onload event to re-trigger a layout()

**Comment by jayelkaake** [comment]
To solve this I did this, where `masonryElement` is an `HTMLElement` that your masonry is attached to and `masonryInstance` is the masonry object instance:
`masonryElement.querySelectorAll('img').forEach((img) => img.addEventListener('load', () => masonryInstance.layout()))`

I also debounced this to avoid updates too frequently.

**Comment by Spope** [comment]
Thanks for your comment, this and the debounce looks like good to me, I'm going to close this issue.
