### ISSUE TITLE
problem when the height of the brick depends on its width

### ISSUE THREAD

**Issue by lhapaipai** [Spope/MiniMasonry.js#2]
Hello !
Another little suggestion...

In my case, the height of each brick depends on its width (an image with a ratio). It's therefore important to define the new width of each brick before calculating its height (when you construct the array `_sizes`.) ?

l-87
```javascript
for (var k = 0;k< children.length; k++) {
    children[k].style.width = Math.round(width) + 'px';
    this._sizes[k] = children[k].clientHeight;
}
```
have a good day

**Comment by Spope** [comment]
Hello, thanks again for your contribution !
This lib was first built to address a specific need and it's great to see contributions like this to make it more generic.
I'm definitely going to do this.
