### ISSUE TITLE
basewidth appears to have no effect.

### ISSUE THREAD

**Issue by DarkMG73** [Spope/MiniMasonry.js#4]
Hello.

First, thanks for the nice tool. 

I thought you might want to know that the "basewidth" parameter appears to have no effect.
Using your [CodePen](https://codepen.io/Spope/pen/WNwrpyd), you can recreate the issue there. Add the basewidth parameter and change the value to any number and nothing is different in the display.

**Comment by Spope** [comment]
Hello,

Thanks for the issue, I would indeed like to know if this parameter wasn't working, but it does ! My guess is that you tried "basewidth" instead of "baseWidth". 
I updated the [codepen](https://codepen.io/Spope/pen/WNwrpyd), please tell me if the first example isn't working for you.

**Comment by Spope** [comment]
Closing this issue, feel free to reopen if the provided codepen doesn't works.
