### ISSUE TITLE
When the item has an image, it will collapse

### ISSUE THREAD

**Issue by awnawnawn** [Spope/MiniMasonry.js#9]
When the image in the item **is loaded slowly**, the `MiniMasonry` will directly calculate the `height` of the current entity instead of the image, which leads to the inaccurate height of the `container`

![Snipaste_2021-04-11_15-03-34](https://user-images.githubusercontent.com/47672657/114295457-f8ef2380-9ad7-11eb-85a4-95c3407ef4d7.png)

[Effect link](https://cdpn.io/abawn/fullembedgrid/jOyYgmz?animations=run&type=embed) refresh more times

**Comment by Spope** [comment]
Hi, thanks for filling this issue. I reproduce and will look if I can add a ResizeObserver to prevent this without interferring with the responsive behaviour.
Right now the best solution (practice) is to set height / width on img tag to avoid size change on image loading.

**Comment by awnawnawn** [comment]
> Hi, thanks for filling this issue. I reproduce and will look if I can add a ResizeObserver to prevent this without interferring with the responsive behaviour.
> Right now the best solution (practice) is to set height / width on img tag to avoid size change on image loading.

Thank you for your reply, I think this feature is more difficult to implement, and the loading time of the image is variable.  So I also set the height of each image container to avoid this problem.
